### ISSUE TITLE
About running code on multiple GPUs

### ISSUE THREAD

**Issue by Vermouth7** [Xt-cyh/CoDI-Eval#2]
Hi, thank you very much for your contributions, I am really interested in your work. I tried to run your code on multiple GPUs, but it didn't work when I changed the '--gpus' parameter. And it reports an error about "CUDA out of memory". I have 4 RTX 4090 available and I think this should be able to run. Can you provide a solution for running on multiple GPUs?

About my running environment:
```
python==3.11.9
torch==1.13.0
accelerate==0.32.1
transformers==4.42.3
```

**Comment by Xt-cyh** [comment]
Thank you for you issue.

I'm so sorry to inform you that our current code does not support multiple GPU. The '--gpus' is an invalid parameter, it was not removed from the released version due to our mistake.

If you want to run on multiple GPUs，you can use vllm ([GitHub - vllm-project/vllm: A high-throughput and memory-efficient inference and serving engine for LLMs](https://github.com/vllm-project/vllm)) to deploy an LLMs HTTP server locally, and call it using OpenAI's API ([OpenAI Compatible Server &#8212; vLLM](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)).

Besides this, our work might be a little bit outdated, and if you are interested, you can also try the latest benchmark for LLM instruction-following, such as IFEval ([[2311.07911] Instruction-Following Evaluation for Large Language Models](https://arxiv.org/abs/2311.07911)) and Complex Bench ([Benchmarking Complex Instruction-Following with Multiple Constraints Composition](https://arxiv.org/html/2407.03978v1)).

**Comment by Vermouth7** [comment]
Thanks!
